[package]
name = "sdf-glyphs-rs"
version = "0.1.0"
edition = "2021"

[lib]
name = "sdf_glyphs"
path = "src/lib.rs"

[[bin]]
name = "sdf_glyphs"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.96"
clap = { version = "4.5.31", features = ["derive"] }
flate2 = "1.1.0"
indicatif = "0.17.11"
prost = "0.13.5"
rstar = "0.12.2"
ttf-parser = "0.25.1"

[build-dependencies]
prost-build = "0.13.5"
