[package]
name = "versatiles_glyphs"
version = "0.1.0"
edition = "2021"

[lib]
name = "versatiles_glyphs"
path = "src/lib/mod.rs"

[[bin]]
name = "versatiles_glyphs"
path = "src/main.rs"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = true
debug-assertions = true
codegen-units = 1
panic = "unwind"
incremental = false
overflow-checks = false
strip = true

[dependencies]
anyhow = { version = "1.0.96", default-features = false }
clap = { version = "4.5.31", default-features = false, features = [
	"derive",
	"std",
] }
indicatif = { version = "0.17.11", default-features = false }
prost = { version = "0.13.5" }
rstar = { version = "0.12.2", default-features = false }
ttf-parser = { version = "0.25.1", default-features = false, features = [
	"std",
] }

[build-dependencies]
prost-build = { version = "0.13.5", default-features = false }
