name: Continuous Integration

on:
  push:
    branches:
      - "**"
    tags:
      - "!**" # Don't run twice on commits with tags
    paths-ignore:
      - "scripts/**"
      - "**.md"
  pull_request:
  schedule:
    - cron: "15 6 * * 2"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Install protobuf-compiler
        run: sudo apt-get install protobuf-compiler

      - name: Check out
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Init Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run fmt
        run: cargo fmt -- --check

      - name: Run check
        run: cargo check --workspace --all-features --all-targets

      - name: Run clippy /
        run: cargo clippy --workspace --all-features --all-targets -- -D warnings

      - name: Run test /
        run: cargo test --workspace --all-features --all-targets

      - name: Install Cargo Coverage
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Cargo Coverage
        run: cargo llvm-cov test --workspace --all-features --tests --lcov --output-path ./lcov.info

      - name: Upload Coverage
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
