name: Release Binaries

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: aarch64-apple-darwin
          - target: aarch64-pc-windows-gnullvm
          - target: aarch64-unknown-linux-gnu
          - target: aarch64-unknown-linux-musl
          - target: x86_64-apple-darwin
          - target: x86_64-pc-windows-gnullvm
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Add Target
        run: rustup target add ${{ matrix.target }}

      - name: Compile
        run: cargo build --release --bins --features="cli" --target ${{ matrix.target }}

      - name: Archive
        run: tar -czf ${{ matrix.target }}.tar.gz -C target/${{ matrix.target }}/release versatiles_glyphs

      - name: Upload
        run: gh release upload "${{ github.ref_name }}" ${{ matrix.target }}.tar.gz --clobber
