name: Release Binaries

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GH_TOKEN: ${{ github.token }}

jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
          - target: x86_64-apple-darwin
    steps:
      - name: Install protobuf-compiler
        run: sudo apt-get install protobuf-compiler

      - name: Check out
        uses: actions/checkout@v4

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          EXTRA_COMMAND_FLAGS: "--features=cli"
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: "tar.gz"
# cargo build --release --bins --features="cli" --target $RUSTTARGET $EXTRA_COMMAND_FLAGS
